### ISSUE TITLE
0.9.2 is a  broken version for multiple projects we use

### ISSUE THREAD

**Issue by ran-isenberg** [rubik/xenon#57] opened 2024-10-21 07:16 UTC
Hi, I love the tools, it's really great but the last version is not working at all. I suspect it's due to the pytoml parsing.
I started to debug, and found  a couple of issues:
1. I provide args and dont wish to use the pytoml integration, yet it fails on extra \n when tryin to parse the pytoml. i had to manually remove extra \n at the end of a list of parameters ( a = [ a, b, c, \n], but again, if you get args, dont bother with parsing the file and please improve the parsing.
2. after i solved that i got this error: AttributeError: 'Namespace' object has no attribute 'url'  - i didnt provide the -u so why does it fail parsing?
here is how i run it:
poetry run xenon --max-absolute B --max-modules A --max-average A -e 'tests/*,.venv/*,cdk.out/*,node_modules/*' 
-p .

here's the pytoml:
https://github.com/ran-isenberg/aws-lambda-handler-cookbook/blob/main/pyproject.toml

Thanks!

**Comment by ran-isenberg** [comment] 2024-10-21 07:17
@rubik  waiting for your feedback :)

**Comment by rubik** [comment] 2024-10-21 07:29
@ran-isenberg Thanks for the report, I'll investigate. Do you remember which version you used before?

**Comment by ran-isenberg** [comment] 2024-10-21 07:32
yes, 0.9.1 according to https://github.com/ran-isenberg/aws-lambda-handler-cookbook/blob/main/poetry.lock

**Comment by Anvil** [comment] 2024-10-21 08:29
* `url` is not the only parameter triggering `AttributeError`, same goes for `exclude` and `ignore`. (I've stopped trying after that)
* We're using poetry with multiple source repositories and xenon fails to parse the file. `configparser.DuplicateSectionError: While reading from 'pyproject.toml' [line 52]: section '[tool.poetry.source]' already exists`. According to poetry documentation this is a regular case.

**Comment by Anvil** [comment] 2024-10-21 08:30
BTW, I'm a bit surprised to see so much breaking changes while switching from a patch version to another.

**Comment by rubik** [comment] 2024-10-21 10:25
@Anvil These breaking changes are not intended, they are bugs resulting from some `pyproject.toml` parsing issues.

@ran-isenberg It appears that `pyproject.toml` is much more flexible than the scenarios covered by #41, which had tests for simple cases. I am able to reproduce the issue above and I confirmed that it's resolved by reverting that PR. I'll release a new minor version shortly. @DolajoCZ FYI

**Comment by rubik** [comment] 2024-10-21 10:32
I released version 0.9.3 with the change reversal. Also, paths can be provided as positional arguments again. Apologies for the issues caused.

**Closed by rubik** 2024-10-21 10:32 UTC
