### ISSUE TITLE
Latest version of radon causes weird warnings with xenon 0.5.2

### ISSUE THREAD

**Issue by spmaniato** [rubik/xenon#19] opened 2017-09-06 18:28 UTC
Running `xenon` (version `0.5.1` or `0.5.2` with `mando-0.3.3` and `radon-1.4.2`) on our code base (Python 2.7) works as expected. But as of very recently, the latest dependencies (`mando-0.6.4`  and `radon-2.0.3`) are causing weird warnings of this form:

```
WARNING:xenon:cannot parse path/to/source.py: invalid syntax (<unknown>, line 1)
```

There is nothing wrong with those (dozens of) files. Downgrading to `radon-1.4.2` gets rid of the warnings.

Not a critical issue, but figured worth opening a ticket for :slightly_smiling_face: Thanks!

PS1. I just confirmed that `radon-2.0.2` works. The issue was introduced in `radon-2.0.3` :information_source: 
PS2. Oops, looks like there was already a ticket in `radon`'s issue tracker: https://github.com/rubik/radon/issues/133

**Comment by rubik** [comment] 2017-09-06 19:41
Exactly, that's a regression introduced in the last relase, sorry ;) The issue is the same, but I'll close this one when the other one is fixed.

**Comment by rubik** [comment] 2017-09-07 07:58
I verified and it should work now, with radon 2.1.1. Don't hesitate to open another issue if the problem persists.

**Closed by rubik** 2017-09-07 07:58 UTC
